### PR TITLE
Update the entry point method used to call into PowerShell

### PR DESCRIPTION
**Pull request by daxian-dbw**
PowerShell Core has been refactored to remove the complex logic from PowerShellAssemblyLoadContext to make hosting PowerShell Core more easy. Now the native host can directly call into System.Management.Automation.dll without going through powershell load context.

### CODE REVIEW

**Comment by paulcallen** [comment]
Is there a released version of PowerShell that this works against, or do we need to wait for the next version?
The test infrastructure may break with this change as we do not build PowerShell in order to test PSRP on Linux.

**Comment by daxian-dbw** [comment]
We need to wait for the next release beta.3. After beta.3 is out, I will update the PR by changing the release versions to beta.3 and then you can do the final review.

**Comment by paulcallen** [comment]
thanks

**Comment by paulcallen** [comment]
I am assume this is going to get checked in and you are going to publish new PSRP server packages.
Apparently you broken people as a result of this. Maybe you should have done a transitional change in PowerShell that left the old entry point in place for a release so the transition would have gone smoother.

**Comment by daxian-dbw** [comment]
> Maybe you should have done a transitional change in PowerShell that left the old entry point in place for a release so the transition would have gone smoother.

You are right, that would be better. Lesson learned.

**Comment by daxian-dbw** [comment]
@paulcallen I need to update some .ps1 script to use the beta.3 release of powershell. Will update the PR soon.

**Comment by daxian-dbw** [comment]
For the reference, we made the same change in `pwrshplugin.dll`: https://github.com/PowerShell/PowerShell/blob/6bb12c9df5afa0a2cbbcef1289b2f253875ed50d/src/powershell-native/nativemsh/pwrshplugin/pwrshclrhost.cpp#L56-L60

The idea is that you can call into `System.Management.Automation.dll` without going through `PowerShellAssemblyLoadContext` now.

**Comment by daxian-dbw** [comment]
@TravisEz13 can you please help review the script changes in this PR?

**Pull request merged**
